name: minio
description: Unofficial MinIO Dart Client SDK that provides simple APIs to access any Amazon S3 compatible object storage server.
version: 3.7.3
homepage: https://github.com/xtyxtyx/minio-dart
issue_tracker: https://github.com/xtyxtyx/minio-dart/issues

environment:
  sdk: '>=3.2.6 <5.0.0'

dependencies:
  meta: ^1.16.0
  http: ^1.5.0
  crypto: ^3.0.6
  convert: ^3.1.2
  xml: ^6.6.1
  buffer: ^1.2.3
  intl: ^0.20.2
  mime: ^2.0.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.8
  html: ^0.15.6
